#!/bin/bash

# shellcheck disable=SC1091,SC2162,SC2181

declare -i kernnum=0

. /etc/default/openmediavault

distro="$(lsb_release --codename --short)"
grubconfig="/boot/grub/grub.cfg";
grubdefault="/etc/default/grub";
pvekey="/usr/share/keyrings/proxmox-release-${distro}.gpg"
pverepo="/etc/apt/sources.list.d/pvekernel.list"
repourl=${OMV_PROXMOX_APT_REPOSITORY_URL:-"http://download.proxmox.com/debian/pve"}
repo="pve-no-subscription"


# only 64 bit amd/intel supported
case "$(/usr/bin/arch)" in
  *amd64*|*x86_64*)
    echo "Supported kernel found"
    ;;
  *)
    echo "Unsupported kernel and/or processor"
    exit 1
    ;;
esac

kernelinput="${1}"
if [[ "${kernelinput}" =~ ^[5-6]\.[0-9]{1,2}$ ]]; then
  kernelversion="${kernelinput}"
else
  kernelversion="5.19"
  echo "Invalid kernel version specified.  Using ${kernelversion}"
fi

# add repo list file
echo "deb [arch=amd64 signed-by=${pvekey}] ${repourl} ${distro} ${repo}" > ${pverepo}
apt-get update

# remove conflicting firmware packages
for pkg in linux linux-nonfree ti-connectivity amd-graphics ath9k-htc cavium siano netronome; do
  if dpkg -l firmware-${pkg} > /dev/null; then
    if ! dpkg --purge firmware-${pkg} 2>/dev/null; then
      echo "Failed to remove firmware-${pkg} package.  Exiting..."
      exit 3
    fi
  fi
done

# install kernel and headers
DEBIAN_FRONTEND=noninteractive apt-get --yes --fix-missing install pve-kernel-${kernelversion} pve-headers-${kernelversion} pve-headers
if [ $? -gt 0 ]; then
  echo "Failed to install Proxmox kernel.  Exiting..."
  exit 4
fi

# set newly install proxmox kernel as default
awk '$1 == "menuentry" { print $6 }' ${grubconfig} | while read kernel; do
  if [[ ${kernel} = *"pve'" ]]; then
    echo "Set ${kernel} as default... ${kernnum}"
    sed -i "s/GRUB_DEFAULT=.*/GRUB_DEFAULT=${kernnum}/" ${grubdefault}
    grub-set-default ${kernnum}
    update-grub
    break
  fi
  (( kernnum++ ))
done

echo "Please reboot to use the new kernel."

exit 0
