#!/bin/bash

# shellcheck disable=SC1091,SC2086,SC2162,SC2181

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

declare -i kernnum=0

distro="$(lsb_release --codename --short)"
grubconfig="/boot/grub/grub.cfg";
grubdefault="/etc/default/grub";
pvekey="/usr/share/keyrings/proxmox-archive-keyring.gpg"
pverepo="/etc/apt/sources.list.d/pvekernel.sources"
pverepoold="/etc/apt/sources.list.d/pvekernel.list"
repourl=${OMV_PROXMOX_APT_REPOSITORY_URL:-"http://download.proxmox.com/debian/pve"}
keyurl=${OMV_PROXMOX_KEY_REPOSITORY_URL:-"https://enterprise.proxmox.com/debian/proxmox-archive-keyring-${distro}.gpg"}
repo="pve-no-subscription"


# only 64 bit amd/intel supported
case "$(/usr/bin/arch)" in
  *amd64*|*x86_64*)
    echo "Supported kernel found"
    ;;
  *)
    echo "Unsupported kernel and/or processor"
    exit 1
    ;;
esac

kernelinput="${1}"
if [[ "${kernelinput}" =~ ^[6-7]\.[0-9]{1,2}$ ]]; then
  kernelversion="${kernelinput}"
else
  kernelversion="6.17"
  echo "Invalid kernel version specified.  Using ${kernelversion}"
fi

# delete old .list file
rm -fv "${pverepoold}"

# add repo sources file
cat > "${pverepo}" << EOF
Types: deb
URIs: ${repourl}
Suites: ${distro}
Components: ${repo}
Signed-By: ${pvekey}
EOF

wget --quiet --output-document=- "${keyurl}" | gpg --dearmor > "${pvekey}"
chmod 644 ${pverepo} ${pvekey}
apt-get update

# remove conflicting firmware packages
for pkg in linux-free amd-graphics ath9k-htc cavium siano netronome; do
  if dpkg -l firmware-${pkg} > /dev/null; then
    if ! dpkg --purge firmware-${pkg} 2>/dev/null; then
      echo "Failed to remove firmware-${pkg} package.  Exiting..."
      exit 3
    fi
  fi
done

# install kernel and headers
DEBIAN_FRONTEND=noninteractive apt-get --yes --fix-missing install proxmox-kernel-${kernelversion} proxmox-headers-${kernelversion}
if [ $? -gt 0 ]; then
  echo "Failed to install Proxmox kernel.  Exiting..."
  exit 4
fi

# set newly install proxmox kernel as default
awk '$1 == "menuentry" { print $6 }' ${grubconfig} | while read kernel; do
  if [[ ${kernel} == *${kernelinput}*pve\' ]]; then
    sed -i "s/GRUB_DEFAULT=.*/GRUB_DEFAULT=saved/" ${grubdefault}
    kerndesc=$(grep '^menuentry ' ${grubconfig} | grep "${kernel}" | cut -d"'" -f2)
    if [ -n "${kerndesc}" ]; then
      echo "Set ${kerndesc} as default... ${kernel/\'/}"
      grub-set-default "${kerndesc}"
    else
      echo "Set ${kernel/\'/} as default... ${kernnum}"
      grub-set-default ${kernnum}
    fi
    update-grub
    break
  fi
  (( kernnum++ ))
done

# mark zfs module dirty to ensure the omv-zfs-provider-pve is installed
zfs=$(dpkg -l | awk '$2 == "openmediavault-zfs" { print $1 }')
if [ "${zfs}" = "ii" ]; then
  echo "Marking zfs saltstack module dirty."
  omv_module_set_dirty zfs
fi

echo "Please reboot to use the new kernel."

exit 0
