#!/bin/bash

# shellcheck disable=SC2086

arch="$(dpkg --print-architecture)"
if [ ! "${arch}" = "amd64" ]; then
  echo "Unsupported architecture."
  exit 1
fi

GRUB="/etc/default/grub"
GRUB_CFG="/boot/grub/grub.cfg"

grub_name="${1}"

if [ -z "${grub_name}" ]; then
  echo "No entry specified!"
  exit 2
fi

echo "Boot once :: ${grub_name}"

DEFAULT=$(awk -F "=" '$1 == "GRUB_DEFAULT" { print $2 }' ${GRUB})

if ! grep -q 'GRUB_DISABLE_SUBMENU' ${GRUB}; then
  echo "GRUB_DISABLE_SUBMENU=y" >> ${GRUB}
  update-grub
fi

ENTRY=$(($(grep 'menuentry ' "${GRUB_CFG}" | grep -n "${grub_name}" | head -n1 | cut -f1 -d:) - 1))

echo "Configuring grub to boot once from '${grub_name}' ... ${ENTRY}"

perl -p -i -e "s/GRUB_DEFAULT=.*/GRUB_DEFAULT=saved/g" "${GRUB}"
grub-set-default ${DEFAULT}
update-grub
grub-reboot ${ENTRY}

echo "Done."

exit 0
